services:
    # ログインチェック(認証失敗)
    aw.login_failure_handler:
        class: Aw\EventBundle\EventListener\AuthenticationFailure
        arguments: ['@router', '@session']

    # ログインチェック(認証成功)
    aw.login_success_handler:
        class: Aw\EventBundle\EventListener\AuthenticationSuccess
        arguments: ['@router', '@session', '@security.context']

    # ログフォーマット
    monolog.formatter.session_request:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] %%channel%%.%%level_name%%: %%context%% %%extra%%: %%message%%\n"

    # ロギング書込処理
    monolog.processor.session_request:
        class: Aw\EventBundle\Service\SessionRequestProcessor
        arguments: ['@session']
        tags:
            - { name: monolog.processor, method: processRecord }
