<?php

namespace Aw\EventBundle\Entity\Repository;

use Aw\EventBundle\Entity\Repository\AppEntityRepository;

/**
 * MstRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MstRoleRepository extends AppEntityRepository
{
}
