<?php

namespace Aw\EventBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Type5Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Type5Repository extends EntityRepository
{
}
