<?php

namespace Aw\EventBundle\Entity\Repository;

use Aw\EventBundle\Entity\Repository\AppEntityRepository;

/**
 * UserRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRoleRepository extends AppEntityRepository
{
}
