homepage:
    pattern:  /
    defaults: { _controller: AwEventBundle:Open/TopPage:index }

aw_event:
    resource: "@AwEventBundle/Controller/"
    type:     annotation
    prefix:   /

login_check:
    pattern: /login/check

logout:
    pattern: /logout

adesigns_calendar:
    resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
