app:
    resource: "@AppBundle/Controller/"
    type:     annotation

aw_event:
    resource: "@AwEventBundle/Resources/config/routing.yml"
    prefix:   /

homepage:
    pattern:  /
    defaults: { _controller: AwEventBundle:Default:index }
